name: Build Local and Test

on:
  workflow_dispatch:
  push:
    branches: develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: "Build ENV and execute tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        id: cache-node
        with:
          node-version: 20
          cache: "npm"

      - name: Store Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')"

      - name: Cache Playwright binnaries
        uses: actions/cache@v4
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        if: steps.cache-playwright.outputs.cache-hit != 'true'

      - name: Install Node env
        run: npm ci

      - name: Build Local
        run: |
          cd test-app
          node server.js &

      - name: Execute tests
        run: npm run test