name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-env:
    name: "Build ENV"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Build Local
        run: |
          cd test-app
          node server.js &

  # call-format:
  #   needs: [build-env]
  #   name: Format Code
  #   uses: './.github/workflows/format.yml'
  #   secrets: inherit

  call-tests:
    needs: [build-env]
    name: Execute tests
    uses: "./.github/workflows/execute-tests.yml"
