name: Build and Test

on: 
  workflow_dispatch:
  push:
    branches: develop

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build-env:
      name: "Build ENV and execute tests"
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}

        - name: Build Local
          run: |
            cd test-app
            node server.js &

    cache-node-and-playwright:
      needs: [build-env]
      name: Setup Node env & Playwright
    
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
          with:
            path: './automation-tests'

        - run: tree

        - uses: actions/setup-node@v4
          id: cache-node
          with:
            node-version: 20
            cache: "npm"

        - name: Store Playwright version
          id: playwright-version
          run: echo "::set-output name=version::$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')" 
          working-directory: ./automation-tests
          
        - name: Cache Playwright binnaries
          uses: actions/cache@v3
          id: cache-playwright
          with:
            path: |
              ~/.cache/ms-playwright
            key: ${{ runner.os }}-playwright    

        - name: Install Node env
          run: npm ci
          working-directory: ./automation-tests
          
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
          if: steps.cache-playwright.outputs.cache-hit != 'true'
          working-directory: ./automation-tests

    execute-tests:
      needs: [cache-node-and-playwright]
      name: Execute tests
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
          with: 
            path: ./automation-tests

        - run: npm run test
          working-directory: ./automation-tests
      
