name: Run Local

on:
  workflow_call:

jobs:
  run-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Build Local
        run: |
          cd app
          node server.js &
          echo "LOCALHOST RUNNING"
