name: Execute tests

on: 
  workflow_call:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # call-format: 
  #   name: "Format Code Before Tests"
  #   uses: ./.github/workflows/format.yml

  call-dependencies: 
    name: "Cache deps"
    uses: ./.github/workflows/cache-deps.yml

  build-and-execute-tests:
    needs: [call-dependencies]
    

    name: "Build Local and execute tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Build Local
        run: npm run build

      - name: Run tests
        run: echo "RUNNING TESTS NOW..."
