name: "Cache Node & Playwright dependencies"

on:
  workflow_call:

jobs:
  cache-node:
    name: Setup Node env
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        id: cache-node
        with:
          node-version: 20
          cache: "npm"

  cache-playwrigth:
    name: Setup Playwright
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Store Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')" 

      - name: Cache Playwright binnaries
        uses: actions/cache@v3
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Node env
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        if: steps.cache-playwright.outputs.cache-hit != 'true'
