name: Create Pull Request

on: 
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    name: "Auto Pull request"
    if: "contains(github.event.head_commit.message, 'docs') || contains(github.event.head_commit.message, 'style') || contains(github.event.head_commit.message, 'chore')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: ${{ github.event.head_commit.message }}
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        branch: auto_branch/patch
        title: Automated PR
        labels: automated pr
        delete-branch: true
        signoff: false
        