# auto merging PR from dependabot 
name: Dependabot auto-merge

on: 
  # pull_request:
  workflow_run:
    workflows: ['PR Title Checker', 'Lint', 'Tests']
    types: ['completed'] 

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        # if: contains(github.event.pull_request.title, 'chore(deps)')
        run: gh pr merge --auto --merge --squash "https://github.com/nikolajovancevic/automating-stuff/pull/101"
        # env:
          # PR_URL: ${{github.event.pull_request.html_url}}