name: Deployment scripts

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: echo "Running tests before deployment..."

  deploy: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deploying now!"