name: Execute tests

on:
  workflow_call:

jobs:
  cache-node-and-playwright:
    name: Setup Node env & Playwright

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - run: tree

      - uses: actions/setup-node@v4
        id: cache-node
        with:
          node-version: 20
          cache: "npm"

      - name: Install Node env
        run: npm ci

      - name: Store Playwright version
        id: playwright-version
        run: echo "::set-output name=version::$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')"

      - name: Cache Playwright binnaries
        uses: actions/cache@v3
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        if: steps.cache-playwright.outputs.cache-hit != 'true'

  execute-tests:
    needs: [cache-node-and-playwright]
    name: Execute tests
    runs-on: ubuntu-latest

    steps:
      - run: npm run test
