name: Format

on:
  workflow_call:
  push:
    branches: develop

jobs:
  format-code:
    name: Format Code
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{ts,js,md,yml}
          github_token: ${{ secrets.TOKEN }}
