name: "PR Title Checker"
on:
  pull_request_target:
    branches:
      - develop
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - review_requested
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-pr:
    name: "Check PR format"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          types: |
            feat
            fix
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
            security
            release
            no-release
          # Configure that a scope must always be provided.
          requireScope: true
