name: Execute tests

on: 
  workflow_call:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-cache:
    name: "Cache deps"
    uses: ./.github/workflows/cache-deps.yml

  # call-format: 
  #   name: "Format Code Before Tests"
  #   uses: ./.github/workflows/format.yml

  call-build: 
    name: "Build Localhost env"
    uses: ./.github/workflows/build.yml
  
  execute-tests:
    needs: [call-cache,call-build]
    
    name: "Execute tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "RUNNING TESTS NOW..."
